# Generated by Django 5.1.5 on 2025-01-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_documentgroup_remove_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.documentgroup', verbose_name='Группа'),
        ),
    ]
