# Generated by Django 5.1.5 on 2025-01-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_document_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentgroup',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='Фото'),
        ),
    ]
