# Generated by Django 5.1.5 on 2025-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_documentgroup_options_alter_documentgroup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название спонсора')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт спонсора')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
    ]
