# Generated by Django 5.1.5 on 2025-03-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_document_group_project_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Проект'),
        ),
    ]
