# Generated by Django 5.1.5 on 2025-03-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_documentgroup_documentmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название группы документов'),
        ),
    ]
